all:
	@javac Bases.java
	@javac Node.java
	@javac Queue.java
	@javac PriorityQueue.java
	@javac PriorityQueueTestDriver.java
	@javac Item.java
	@javac Buyer.java 
	@javac Seller.java 
	@javac Assignment2Driver.java
	@java PriorityQueueTestDriver
	@java Assignment2Driver input.txt
	@rm *.class
